services:
  # Сервис для фронтенда
  - type: web
    name: orglink-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run render-build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        value: https://orglink-production-e9d8.up.railway.app
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
    # Настройки для WebSocket
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization"
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
